src/components/views/login/PasswordLogin.js
Changing login method to "email" only.
=> Change login method

package-lock.json, src/components/structures/login/Login.js, src/components/structures/login/Registration.js, src/components/views/login/RegistrationForm.js, src/i18n/strings/en_EN.json, src/i18n/strings/en_US.json, src/i18n/strings/fr.json
Change registration method to implement the automatic selection of the good bubble.
=> Change registration method

src/components/structures/login/Login.js, src/components/views/directory/NetworkDropdown.js
=> Update HomeServer list

package-lock.json, res/css/structures/_RoomDirectory.scss, res/css/structures/_UserSettings.scss, res/css/views/elements/_AddressSelector.scss, res/css/views/rooms/_MemberInfo.scss, res/css/views/rooms/_RoomSettings.scss, res/css/views/rooms/_RoomTile.scss, src/Avatar.js, src/components/structures/RoomDirectory.js, src/components/structures/UserSettings.js, src/components/views/dialogs/AddressPickerDialog.js, src/components/views/dialogs/ConfirmUserActionDialog.js, src/components/views/elements/AddressTile.js, src/components/views/rooms/MemberInfo.js, src/components/views/rooms/RoomSettings.js
- Changes on the background color when selecting a user to start a conversation
- Changes on the color on the permission tag on public room selection
- Changes on some \<H3\> color
- Removing the "Debug Logs Submission" section in Settings
- Hiding the Matrix user address when inviting a user to tchat
- Hiding the Matrix room address listing all the Public Rooms
=> Some small design and UX updates

src/components/structures/LoggedInView.js
Resolve #26 :
Remove the top cookie bar asking to share anonymous data on login.
=> Remove the top cookie bar

src/components/views/rooms/RoomSettings.js
Resolve #25 
Remove the following block inside the rooms options :
- Who can access this room
- Encryption is enabled in this room
- Who can read history
- Addresses
=> Remove some rooms options

src/components/views/rooms/MemberInfo.js, src/components/views/rooms/RoomHeader.js
Resolve #24 
Remove the room's sharing option and the user's sharing option in public room and in 1:1 room.
=> Remove some sharing options

src/components/views/dialogs/CreateRoomDialog.js, src/i18n/strings/en_EN.json, src/i18n/strings/en_US.json, src/i18n/strings/fr.json
Resolve #22 
Make the room title required in rooms creation.
=> Make the room title inside the room creation required

src/components/structures/login/Registration.js
Update the registration URLs and the old discovery method.
Resolve #35
=> Update the registration URLs

package-lock.json, package.json, src/ContentMessages.js, src/components/views/messages/MAudioBody.js, src/components/views/messages/MFileBody.js, src/components/views/messages/MImageBody.js, src/components/views/messages/MVideoBody.js, src/i18n/strings/en_EN.json, src/i18n/strings/en_US.json, src/i18n/strings/fr.json, src/utils/DecryptFile.js
=> Seting up the MCS

src/components/views/rooms/RoomTile.js
Resolve #73 
Take care about the possible conflicts with #68
=> Remove the dmIndicator for direct rooms

src/components/structures/RoomDirectory.js, src/components/views/rooms/RoomDetailRow.js, src/createRoom.js
=> Change the settings for the public room creation

res/css/structures/_LeftPanel.scss
=> Fix the lost of responsivity due to the Marianne logo

src/components/views/rooms/RoomHeader.js
=> Remove the settings button for direct rooms

src/components/views/rooms/RoomHeader.js
=> Remove the search button inside encrypted rooms

src/components/structures/RoomView.js
=> Remove the warning about the beta encryption

src/components/views/messages/MAudioBody.js, src/components/views/messages/MFileBody.js, src/components/views/messages/MImageBody.js, src/components/views/messages/MVideoBody.js, src/utils/ContentScanner.js, src/utils/DecryptFile.js
Rewriting the whole MCS logic.
Resolve #48 
Resolve #60 
Make #61 useless
=> Rewriting the whole MCS logic

src/components/structures/RoomDirectory.js, src/components/structures/login/Login.js, src/components/structures/login/Registration.js, src/components/views/directory/NetworkDropdown.js
=> Externalize home server configuration

src/components/views/rooms/RoomHeader.js
=> Fixing a bug where a user cannot join a public room

src/components/views/messages/MFileBody.js
=> Update the CROSS_ORIGIN_RENDERER with a HS based version

src/components/views/directory/NetworkDropdown.js
=> Change the domain name in the public room dropdown

src/components/views/dialogs/CreateRoomDialog.js
=> Change the domain name in the public room creation

src/components/structures/RoomDirectory.js
=> Change the domain name in the public room list

res/css/views/voip/_IncomingCallbox.scss
=> Change the white on white text on incoming call dialog

src/components/structures/login/Registration.js
=> Remove the username in the initial registration request to fix the pooling

src/components/structures/MatrixChat.js
=> Change the way MatrixChat return a default hs url

src/components/structures/UserSettings.js
Resolve #95 
Maybe it will be reverted later.
=> Remove the 'Share User' option

src/components/structures/login/Login.js
=> Remove the 'Matrix' wording on login error

src/i18n/strings/fr.json
=> Wording things

src/createRoom.js
=> Changing the default power needed to invite someone in a room

src/components/views/dialogs/KeyShareDialog.js, src/i18n/strings/fr.json
=> Update the share keys dialog

src/components/views/rooms/MessageComposer.js
=> Remove the sticker button in the message composer

src/createRoom.js
=> Set the default room visibility to 'invited' for private rooms

src/components/structures/BottomLeftMenu.js, src/settings/Settings.js
=> Change some default users settings

src/components/structures/RoomStatusBar.js, src/i18n/strings/en_EN.json, src/i18n/strings/fr.json
=> Remove the ability to add people when you are alone in a direct room

src/RoomInvite.js, src/components/views/dialogs/AddressPickerDialog.js
=> Remove the ability to add multiple user on direct invitation dialog

src/components/views/rooms/MessageComposer.js
=> Disable the Voip and Video Call

src/RoomInvite.js, src/components/views/dialogs/AddressPickerDialog.js
Reverts dinsic-pim/matrix-react-sdk#132
=> Revert "Remove the ability to add multiple user on direct invitation dialog"

src/RoomInvite.js, src/components/views/dialogs/AddressPickerDialog.js
=> Remove multiple user on direct invitation

src/createRoom.js
=> Fixing a bug where a user cannot join a public room from a different domain

res/css/structures/_UserSettings.scss, src/components/structures/UserSettings.js, src/i18n/strings/en_EN.json, src/i18n/strings/fr.json
=> User settings : add a red list option to user params

src/components/structures/RoomDirectory.js
Fixing a bug where no public rooms are listed when a search is done on public rooms directory.
Resolve dinsic-pim/riot-web#25
=> Bug Fix - Public rooms : No rooms from federation are shown when a search is done

res/css/structures/_RightPanel.scss
=> Bug Fix - Public Rooms : The invite button is hidden on Google Chrome

src/utils/DMRoomMap.js
=> Bug Fix - Public rooms : Sometimes a user cannot join a public room

src/components/structures/BottomLeftMenu.js, src/components/structures/RightPanel.js, src/components/structures/UserSettings.js, src/components/views/rooms/MemberInfo.js
=> Extern users : Configure the application for the extern users

src/RoomInvite.js
=> Bug - Invitations : Update the "which room to pick" algorithm

package-lock.json, package.json
Resolve #179 
Related to dinsic-pim/tchap-web/issues/27
=> Update in order to use the new matrix-js-sdk

src/components/structures/login/Login.js
=> Error Message - Login : Change the login error message when the email is unauthorized

src/Users.js, src/components/structures/BottomLeftMenu.js, src/components/structures/RightPanel.js, src/components/structures/UserSettings.js, src/components/views/rooms/MemberInfo.js
Move `_isUserExtern` and `_isUserExternFromUserId` in a Users dedicated file.
=> Update : Mutualise extern functions

src/stores/RoomListStore.js
=> Update - Room list : Hide the partially created rooms from email invitations

src/RoomInvite.js, src/components/views/dialogs/InformationDialog.js, src/i18n/strings/en_EN.json, src/i18n/strings/fr.json
Rewriting of the whole "Room picking" algorithm and add email support for future uses.
Resolve #184 
Resolve #177
=> Update - Room picking algorithm : Rewrite of the whole algorithm and add the email support

src/components/structures/UserSettings.js, src/components/structures/login/ForgotPassword.js
=> Bug Fix - Forgot password : Use discoverTchapPlatform() on forgot password

src/components/views/rooms/RoomList.js
=> Left menu : Remove "History" section on left menu

src/components/structures/UserSettings.js
=> User params : Remove the phone number section

src/components/structures/login/Registration.js, src/components/views/settings/ChangePassword.js
=> Global : Increase the min length of the password

src/components/structures/HomePage.js
=> Update - Extern Users : Hide some Homepage shortcuts

src/Users.js
=> Update - Extern Users : Update isUserExtern() function

src/components/structures/RoomStatusBar.js, src/components/views/dialogs/KeyShareDialog.js
Update Share Keys features
* #105 
* #135 
=> [Tchap-v2] Update Share Keys features

res/themes/tchap/css/_fonts.scss, res/themes/tchap/css/_paths.scss, res/themes/tchap/css/_tchap.scss, res/themes/tchap/css/tchap.scss, src/components/views/settings/tabs/user/GeneralUserSettingsTab.js, src/i18n/strings/en_EN.json, src/i18n/strings/fr.json, src/settings/Settings.js, src/settings/controllers/ThemeController.js
=> [Tchap-v2] (Design) Prepare files for theming

src/linkify-matrix.js
Add "noreferrer nofollow noopener" on MessageComposer generated links
=> Message composer : Add a no referrers option on links

src/RoomInvite.js, src/components/views/dialogs/AddressPickerDialog.js, src/components/views/elements/AddressSelector.js
Update invitation dialog
* #151 
=> [Tchap-v2] Update invitation dialog

src/components/views/dialogs/UserSettingsDialog.js, src/components/views/settings/tabs/user/GeneralUserSettingsTab.js, src/i18n/strings/en_EN.json, src/i18n/strings/fr.json
A new option "Red list" is added in the profile settings.
- #170 
=> [Tchap-v2] Red list option

src/SlashCommands.js
Remove the /devtools command
Resolve #221
=> MessageComposer : Remove /devtools command

src/RoomInvite.js, src/Tchap.js, src/components/views/dialogs/AddressPickerDialog.js, src/components/views/rooms/RoomPreviewBar.js
=> Use proxy lookup

src/components/views/elements/AppTile.js, src/components/views/messages/MFileBody.js, src/linkify-matrix.js
Adding 'noreferrer nofollow noopener' to every 'target: _blank' links.
- #214 
=> [Tchap-v2] Adding 'noreferrer nofollow noopener' to every 'target: _blank' links

src/RoomInvite.js, src/Tchap.js, src/components/structures/RoomSubList.js, src/components/views/rooms/MemberInfo.js, src/components/views/rooms/MemberList.js, src/components/views/settings/tabs/user/GeneralUserSettingsTab.js, src/i18n/strings/en_EN.json, src/i18n/strings/fr.json
Extern users management.
Change "Start a chat" right menu option.
- #173 
- #191 
- #206 
- #225 
=> [Tchap-v2] Extern users management

src/RoomInvite.js, src/Tchap.js, src/components/structures/RoomSubList.js, src/components/views/rooms/MemberInfo.js, src/components/views/rooms/MemberList.js, src/components/views/settings/tabs/user/GeneralUserSettingsTab.js, src/i18n/strings/en_EN.json, src/i18n/strings/fr.json
Reverts dinsic-pim/matrix-react-sdk#226
=> Revert "[Tchap-v2] Extern users management"

src/RoomInvite.js, src/Tchap.js, src/TchapApi.js, src/components/views/dialogs/AddressPickerDialog.js, src/components/views/rooms/RoomPreviewBar.js
Setting-up the new lookup api.
- #227 
=> [Tchap-v2] Update lookup function

src/RoomInvite.js, src/components/views/rooms/MemberInfo.js, src/i18n/strings/en_EN.json, src/i18n/strings/fr.json
Change the "Start a chat" right menu option
Resolve #217
=> Right Menu - Member Infos : Change "Start a chat" right menu option

res/img/tchap/padlock-encrypted_room.svg, src/components/views/context_menus/TopLeftMenu.js, src/components/views/rooms/EventTile.js, src/components/views/rooms/MemberInfo.js, src/components/views/rooms/ReadReceiptMarker.js, src/components/views/rooms/RoomTile.js, src/i18n/strings/en_EN.json, src/i18n/strings/fr.json, src/stores/RoomListStore.js
Update some display features.
* #89 
* #185 
* #118 
* #139 
=> [Tchap-v2] Update some display features

src/components/views/rooms/RoomList.js
Remove "Historical" section on the left menu.
- #195 
=> [Tchap-v2] Remove "Historical" section

src/components/structures/auth/Login.js, src/components/views/auth/LanguageSelector.js, src/components/views/dialogs/CreateRoomDialog.js
Update code in order to follow the new config.json file.
See https://github.com/dinsic-pim/tchap-web/pull/36 and #201 for more informations.
=> [Tchap-v2] Update code in order to follow the new config.json file

src/components/views/settings/Notifications.js
=> User Options - Notifications : Remove "Email notifications"

src/components/views/context_menus/RoomTileContextMenu.js, src/components/views/settings/Notifications.js
Remove "Settings" in room dropdown menu.
Remove "Email notifications" options.
- #236 
=> [Tchap-v2] Remove setting in room dropdown menu and "email notifications" options

src/SlashCommands.js, src/components/views/settings/tabs/room/AdvancedRoomSettingsTab.js
Removing /devtools slash command and DevTools button.
Maybe there is some additional slash commands to remove.
What to do about : 
- /upgraderoom
- /nick
- /roomnick
- /addwidget
- /discardsession
- /invite
Related to 
- #222 
=> [Tchap-v2] Removing some slash commands

src/components/structures/UserSettings.js
Re-enabling red list parameter for Extern users.
Resolve dinsic-pim/tchap-web#37
=> Enabling red list parameter for Extern users

src/autocomplete/Components.js, src/components/views/avatars/BaseAvatar.js, src/components/views/elements/Pill.js, src/components/views/messages/SenderProfile.js, src/components/views/rooms/EntityTile.js, src/components/views/rooms/ReadReceiptMarker.js
Removing some remaining userId.
=> [Tchap-v2] Removing some remaining userId

src/components/views/settings/tabs/user/GeneralUserSettingsTab.js, src/i18n/strings/en_EN.json, src/i18n/strings/fr.json
=> [Tchap-v2] User params : Warn external users when disabling red list option

src/Tchap.js, src/TchapApi.js, src/components/structures/MatrixChat.js, src/components/views/dialogs/ExpiredAccountDialog.js
See dinsic-pim/tchap-web#40 and #245
=> [Tchap-v2] Life email management

src/Tchap.js, src/components/structures/MatrixChat.js, src/components/views/dialogs/ExpiredAccountDialog.js, src/i18n/strings/en_EN.json, src/i18n/strings/fr.json
Life email management.
Resolve dinsic-pim/tchap-web#40
Resolve #245
=> Life email management

src/components/structures/UserSettings.js, src/i18n/strings/en_EN.json, src/i18n/strings/fr.json
=> User params : Warn external users when disabling red list option

src/components/views/dialogs/BugReportDialog.js, src/components/views/dialogs/SessionRestoreErrorDialog.js, src/components/views/dialogs/StorageEvictedDialog.js, src/components/views/dialogs/TimelineExplosionDialog.js
=> [Tchap-v2] Global : Update bug_report_endpoint_url

src/components/structures/UserSettings.js, src/components/views/dialogs/BugReportDialog.js, src/components/views/dialogs/SessionRestoreErrorDialog.js
=> Global : Update bug_report_endpoint_url

package.json, src/components/views/settings/tabs/user/HelpUserSettingsTab.js
=> [Tchap-v2] Version things

src/components/views/rooms/EntityTile.js
Resolve dinsic-pim/tchap-web#47
=> [Tchap-v2] Remove the faded effect on username on users list in a room

src/components/views/rooms/RoomHeader.js
Resolve dincsi-pim/tchap-web#45
=> [Tchap-v2] Remove Integs button

src/components/views/rooms/MessageComposer.js
Resolve dinsic-pim/tchap-web#44
=> [Tchap-v2] Disable video and audio call

res/css/views/rooms/_E2EIcon.scss, src/components/views/rooms/E2EIcon.js
Resolve dinsic-pim/tchap-web#50
=> [Tchap-v2] Change the color and the appearances of "Untrusted devices" padlock on room name

src/components/views/settings/tabs/user/SecurityUserSettingsTab.js
Change the order of the subsections on security settings tab.
=> [Tchap-v2] Change the order of the subsections on security settings tab

src/Tchap.js, src/components/views/context_menus/RoomTileContextMenu.js, src/components/views/rooms/RoomSettings.js, src/i18n/strings/en_EN.json, src/i18n/strings/fr.json
=> Room leave : Warn the last admin when he try to leave a room

src/Tchap.js, src/components/views/context_menus/RoomTileContextMenu.js, src/components/views/settings/tabs/room/GeneralRoomSettingsTab.js, src/i18n/strings/en_EN.json, src/i18n/strings/fr.json
=> [Tchap-v2] Warn the last admin when he try to leave a room

res/css/structures/_RightPanel.scss
Fix "invite" button on google chrome.
=> Room : Fix "invite" button on google chrome

res/css/structures/_RoomSubList.scss, res/css/views/rooms/_EventTile.scss, res/css/views/rooms/_RoomTile.scss
=> [Tchap-v2] Small design update

src/components/views/messages/UnknownBody.js, src/i18n/strings/en_EN.json, src/i18n/strings/fr.json
=> [Tchap-v2] Update wording

src/components/structures/LeftPanel.js, src/components/views/settings/tabs/user/PreferencesUserSettingsTab.js
Resolve dinsic-pim/tchap-web#62
=> Left Bar : Disable left tagPanel

src/components/structures/auth/ForgotPassword.js, src/components/views/auth/PasswordLogin.js, src/components/views/auth/RegistrationForm.js
For every email input, transform the email to a lowercase version before sending it to the server.
Resolve dinsic-pim/tchap-web#64
Resolve  dinsic-pim/tchap-web#53
=> Email Input : Send a lowercase email to the server

src/components/views/dialogs/UserSettingsDialog.js, src/settings/Settings.js
-  Remove "Voice & Video" tab
-  Disable "Enable inline URL previews by default" and hide it inside "Preferences" tab
Resolve dinsic-pim/tchap-web#59
=> Settings view : Update some features

src/components/views/rooms/EventTile.js
Do not allow to redact any state event.
Resolve dinsic-pim/tchap-web#56
=> Room : Do not allow to redact the event that enabled encryption in a room

src/components/views/dialogs/BugReportDialog.js, src/components/views/settings/tabs/user/HelpUserSettingsTab.js, src/i18n/strings/en_EN.json, src/i18n/strings/fr.json
Change the wording and the way that the Bug Report works.
Resolve dinsic-pim/tchap-web#68
=> Bug Report : Update the bug report flow and wording

src/stores/RoomListStore.js
On the room list, change "Empty room (was...)" by the name of the user who has left.
Resolve dinsic-pim/tchap-web#66
=> Udpade "Empty room (was...)" by the name of the user who has left

src/components/structures/auth/Login.js, src/components/structures/auth/Registration.js, src/i18n/strings/en_EN.json, src/i18n/strings/fr.json
Add a wording for M_LIMIT_EXCEEDED and ERR_UNREACHABLE_HOMESERVER on login or register.
Resolve dinsic-pim/tchap-web#67
=> Error : Add a wording for M_LIMIT_EXCEEDED and ERR_UNREACHABLE_HOMESERVER

res/css/views/rooms/_RoomHeader.scss, res/themes/dark/css/_dark.scss, res/themes/light/css/_light.scss, res/themes/tchap/css/_tchap.scss, src/components/views/rooms/RoomHeader.js, src/i18n/strings/en_EN.json, src/i18n/strings/fr.json
On the room header, near the room name, show the access rule (external restricted).
Disable the access to rooms options when clicking on the title.
Resolve dinsic-pim/tchap-web#63
=> Room Header : Add AccessRule on room header

src/components/views/auth/RegistrationForm.js, src/i18n/strings/en_EN.json, src/i18n/strings/fr.json
During the registration flow, show a warning if the user try to create an external account.
Resolve dinsic-pim/tchap-web#69
=> Registration : Warn user when he try to create an external account

src/stores/RoomListStore.js
#278 bug fix
Resolve dinsic-pim/tchap-web#70
=> Room List : Fix #278 new bug

res/themes/tchap/css/_tchap.scss, src/components/views/settings/tabs/user/HelpUserSettingsTab.js
Small design update and remove the Credit inside Parameters.
Resolve dinsic-pim/tchap-web#60
=> Small design update

src/Tchap.js, src/components/views/auth/RegistrationForm.js, src/components/views/dialogs/AddressPickerDialog.js, src/i18n/strings/en_EN.json, src/i18n/strings/fr.json
Resolve dinsic-pim/tchap-web#74
=> Room Invite : Fix the message when trying to invite an extern on a restricted room

src/RoomInvite.js
Resolve dinsic-pim/tchap-web#75
=> DM Invite : Fix the message when trying to invite a user by email

src/components/structures/MatrixChat.js, src/components/views/context_menus/RoomTileContextMenu.js
Resolve dinsic-pim/tchap-web#76
=> Room Leave : Fix the modal shown when a direct room is left 

src/RoomInvite.js, src/i18n/strings/en_EN.json, src/i18n/strings/fr.json
=> i18n : Wording

src/Tchap.js, src/components/views/rooms/RoomTile.js
Resolve dinsic-pim/tchap-web#80
=> Bug fix : "Restricted" border on room avatar are not correctly shown

src/components/views/dialogs/LogoutDialog.js, src/components/views/settings/tabs/user/SecurityUserSettingsTab.js, src/settings/Settings.js
Temporarily disable Key Backup.
=> Global : Temporarily disable Key Backup

res/css/views/rooms/_EventTile.scss, res/css/views/rooms/_RoomTile.scss, res/themes/light/css/_light.scss, res/themes/tchap/css/_tchap.scss, src/async-components/views/dialogs/EncryptedEventDialog.js, src/i18n/strings/en_EN.json, src/i18n/strings/fr.json
Update desing + change some wording
=> Update desing + change some wording

src/Tchap.js, src/components/views/dialogs/AddressPickerDialog.js
=> Reorganizing Tchap Class

src/Tchap.js, src/TchapApi.js
=> Reorganizing Tchap Class 2

src/components/structures/RoomDirectory.js
Resolve dinsic-pim/tchap-web#81
=> Public room list : Fix the bug if an HS is unavailable

src/components/views/elements/AddressSelector.js
Resolve dinsic-pim/tchap-web#82
=> User search : Show the users from my instance first

src/components/views/settings/tabs/room/GeneralRoomSettingsTab.js, src/i18n/strings/en_EN.json, src/i18n/strings/fr.json
Resolve dinsic-pim/tchap-web#84
Here is an exemple of what the UI looks like.
It's possible to simplify it if needed.
=> Room : Add the ability to change a room visibility from public to private

src/components/views/rooms/RoomPreviewBar.js, src/i18n/strings/fr.json
Add some missing translations.
=> Translation : Add some translations

src/components/views/context_menus/MessageContextMenu.js, src/components/views/dialogs/ShareDialog.js, src/i18n/strings/en_EN.json, src/i18n/strings/fr.json, src/matrix-to.js
Re-enable permalink for messages and rooms.
Resolve dinsic-pim/tchap-web#83
=> Room : Enable permalink for messages and rooms

src/components/structures/auth/Login.js, src/i18n/strings/en_EN.json, src/i18n/strings/fr.json
Resolve dinsic-pim/tchap-web#85
=> Wording : Update the "M_LIMIT_EXCEEDED" wording

src/components/views/elements/AddressSelector.js
Reverts dinsic-pim/matrix-react-sdk#300
=> Revert "User search : Show the users from my instance first"

src/components/views/auth/InteractiveAuthEntryComponents.js
Resolve dinsic-pim/tchap-web#91
=> Registration : Fix bad url when register for the first time on a fresh browser

src/components/views/elements/Pill.js
Resolve dinsic-pim/tchap-web#92
=> Room : Fix undefined member inside pills

res/css/views/rooms/_EntityTile.scss, res/css/views/rooms/_MemberInfo.scss, src/Tchap.js, src/TchapApi.js, src/components/views/rooms/EntityTile.js, src/components/views/rooms/MemberInfo.js, src/components/views/rooms/MemberList.js
Resolve dinsic-pim/tchap-web#89
=> User list : Use the Expire api in order to change the deactivated users color in users list

src/RoomInvite.js
Resolve dinsic-pim/tchap-web#99
=> Invitation : Fix the error due to email invitation

src/RoomInvite.js
Resolve dinsic-pim/tchap-web#105
=> Invite dialog : Revert deactivation of email in public room invite

src/components/views/rooms/EntityTile.js
Temporary disable Expired API uses
Will be reworked.
See dinsic-pim/tchap-web#101
See dinsic-pim/matrix-react-sdk#315
=> Temporary disable Expired API uses

src/components/views/messages/MFileBody.js
Temporary remove the origin param for thumbnails.
=> Remove the origin param for thumbnails

src/settings/Settings.js
Resolve dinsic-pim/tchap-web#110
=> Settings : Change default setting for Room order

src/components/views/dialogs/CreateRoomDialog.js
Resolve dinsic-pim/tchap-web#113
=> Room creation : Change default value for federated option on public room creation

src/HtmlUtils.js, src/SlashCommands.js, src/components/views/elements/Pill.js, src/components/views/rooms/MessageComposerInput.js, src/linkify-matrix.js, src/matrix-to.js
[Edit2] : As mentioned by @giomfo https://github.com/dinsic-pim/matrix-react-sdk/pull/309#issuecomment-626568518 a rework is needed in order to keep some matrix.to 
[Edit] : This PR remove the matrix.to mechanism 
Catch tchap.gouv.fr links inside the Tchap app instead of opening it inside a new tab.
Related to dinsic-pim/tchap-web#83
=> Global : Remove the matrix.to mechanism 

src/components/structures/LoggedInView.js, src/components/views/dialogs/InfoEncryptionDialog.js, src/components/views/dialogs/LogoutDialog.js
Resolve dinsic-pim/tchap-web#117
=> Post Login Modal : Only show it after a real login

src/components/views/elements/Pill.js
Resolve dinsic-pim/tchap-web#118
Need #309 to be merged.
=> Room timeline : Fix Room mentions

src/components/tchap/views/dialogs/InviteFromFileDialog.js
Resolve dinsic-pim/tchap-web#124
=> Invite From file : Fix a bug with the /info request

src/components/views/messages/MFileBody.js, src/i18n/strings/en_EN.json, src/i18n/strings/fr.json
Resolve dinsic-pim/tchap-web#125
=> Decrypt file : Adding a loading wheel during de decrypt phase of a file

src/components/views/rooms/RoomHeader.js
Resolve dinsic-pim/tchap-web#122
=> Room Preview : Remove the "Param" button if my membership is not "join"

src/components/views/elements/DeviceVerifyButtons.js
Resolve dinsic-pim/tchap-web#123
=> Member Device Info : Remove "Blacklist" and "Verify" button

src/components/views/settings/DevicesPanelEntry.js
Resolve dinsic-pim/tchap-web#128
=> Devices List : Hide shown IP

src/components/views/room_settings/RoomProfileSettings.js, src/createRoom.js
Resolve dinsic-pim/tchap-web#127
=> Global : Increase alias random string length

src/components/views/room_settings/RoomProfileSettings.js
Resolve dinsic-pim/tchap-web#129
=> Room Settings : Disable links sharing for the moment

src/components/views/room_settings/RoomProfileSettings.js
Re-enable link sharing option.
=> [Global] Re-enable link sharing option

src/components/views/auth/RegistrationForm.js
Resolve dinsic-pim/tchap-web#131
=> [Registration] Fix the password helper string

src/RoomInvite.js
Resolve dinsic-pim/tchap-web#132
=> [Invite to room] Fix a badly shown modal

src/components/views/rooms/MemberInfo.js
Resolve dinsic-pim/tchap-web#133
=> [Invite from room] Fix a bug if you invite a user to a 1:1 from a room nothing happens

src/TextForEvent.js, src/i18n/strings/en_EN.json, src/i18n/strings/fr.json
Resolve dinsic-pim/tchap-web#134
=> [Room History] Hide useless messages on room creation

src/components/views/context_menus/MessageContextMenu.js
Resolve dinsic-pim/tchap-web#136
=> [Message Context Menu] Hide some useless entries

res/css/_common.scss, src/components/structures/MatrixChat.js, src/components/views/dialogs/ExpiredAccountDialog.js
Resolve dinsic-pim/tchap-web#137
=> [Expired Account Modal] Hide background errors

src/createRoom.js
Resolve dinsic-pim/tchap-web#126
=> [Room creation] Do not override the power levels anymore

src/RoomInvite.js, src/components/views/dialogs/ConfirmUserActionDialog.js
Resolve dinsic-pim/tchap-web#147
=> [Invite error modal] Replace MxId to Name on the "Invite error" modal

src/components/views/rooms/EventTile.js
Resolve dinsic-pim/tchap-web#146
=> [Room Timeline] Remove the "Unencrypted message" mention for room state events

src/components/views/context_menus/RoomTileContextMenu.js, src/components/views/rooms/RoomList.js, src/i18n/strings/en_EN.json, src/i18n/strings/fr.json
Resolve dinsic-pim/tchap-web#143
=> [Global] Change wording 'Favourite' to 'Pin' for rooms

src/RoomInvite.js, src/Tchap.js, src/components/views/rooms/MemberInfo.js, src/components/views/rooms/RoomHeader.js, src/components/views/rooms/RoomList.js, src/components/views/rooms/RoomTile.js, src/i18n/strings/en_EN.json, src/i18n/strings/fr.json, src/stores/RoomListStore.js
Resolve dinsic-pim/tchap-web#144
=> [Global] Prepare UI for "Tchap Info" room

src/components/views/settings/tabs/room/GeneralRoomSettingsTab.js, src/components/views/settings/tabs/user/PreferencesUserSettingsTab.js
Resolve dinsic-pim/tchap-web#138
=> [Settings] Disable URL preview

src/Tchap.js
Resolve dinsic-pim/tchap-web#149
=> [Global] Fix http request timeout

src/components/structures/ScrollPanel.js
Fixing an "cannot read property xx on undefined'.
=> [Timeline] Fixing a bug on ScrollPanel

src/components/tchap/views/dialogs/InviteFromFileDialog.js
Resolve dinsic-pim/tchap-web#153
=> [Invite from file] Add .csv to selectable file type

src/RoomInvite.js, src/components/structures/MatrixChat.js, src/components/structures/RoomDirectory.js
Fixing bugs : 
- Add a protection on getting `rawDisplayName` in invite error
- Add a protection on getting error in expired account verification
- Continue the parsing when the server answer `M_UNAUTHORIZED` on getting public rooms
=> [Global] Multiple bug fix

src/components/views/dialogs/CreateRoomDialog.js
Disable the switch "Limit access to this room to domain members" for agent.agent HS users.
Resolve dinsic-pim/tchap-web#121
=> [Room Creation] Improve room creation UI for agent.agent HS users

src/async-components/views/dialogs/ExportE2eKeysDialog.js, src/i18n/strings/en_EN.json, src/i18n/strings/fr.json
Resolve dinsic-pim/tchap-web#154
=> [Export Key Dialog] Update passphrase min length to 8

src/components/views/messages/TextualBody.js, src/components/views/rooms/AppsDrawer.js
=> [Global] Disable Scalar api calls

src/Tchap.js, src/components/views/messages/TextualBody.js
Resolve dinsic-pim/tchap-web#155
=> [Message Composer] Transform room urls into room pill

.gitignore, src/Tchap.js
Uses Promise.race in Tchap.discoverPlatform() in order to do less requests and speed up login process.
=> Uses Promise.race in discoverPlatform()

package.json
See https://github.com/tchapgouv/tchap-web/pull/168 for discussion
=> Add Scalingo builds

src/components/views/rooms/MemberInfo.js
Hopefully close tchapgouv/tchap-web#194.
=> Replace Invite with Send A Message in user profile details

src/components/views/rooms/MemberInfo.js
En rapport avec tchapgouv/tchap-web#217
=> Hide Send a Message Link for externals

src/components/views/auth/InteractiveAuthEntryComponents.js, src/components/views/dialogs/IncomingSasDialog.js
https://github.com/tchapgouv/tchap-web/issues/188
=> Fix last translations for 2.4.0

res/css/views/avatars/_BaseAvatar.scss, res/css/views/rooms/_RoomTile.scss, src/components/views/rooms/RoomTile.js
The class "mx_RoomTile_avatar_room" was made to show an hexagon.
This will uniform the client Web with Android.
=> Remove hexagon
